baseURL = 'https://polymorph.co/'
languageCode = 'en-us'
title = 'Polymorph'
theme = 'coder'
environment = "production"
enableEmoji = true

[pagination]
pagerSize = 6

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Polymorph"
description = "AI testing and stressing services"
keywords = "AI,testing,stressing,automation"
info = ["AI Testing & Stressing Platform"]
dateFormat = "January 2, 2006"
colorScheme = "auto"
hideColorSchemeToggle = false

[taxonomies]
category = "categories"
tag = "tags"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"